name: Demo 
on : 
    push:
        branches:
            - master
jobs:
    test:
        runs-on : ubuntu-latest
        steps:
            - name: Code Checkout 
              uses : actions/checkout@v3
            - name: Demo
              run : echo " Hello Kiran " 
            - name : Demo2 
              run :  echo " hello my secert is $DOLO "
        env :
            DOLO : ${{secrets.DOLO}}