name : Test Workflow
on :
    workflow_dispatch:
        inputs:
            name:
                description : "Deployment environment Staging or production"
                required : true
                default :  "Staging"
                type : string
            version:
                description: "App version to deploy"
                required: false
                default: "latest"
                type: string
jobs:
    test:
        runs-on : ubuntu-latest
        env:
            data : "Kiran Gowda "
            fame : "Start"
        steps:
            - name: Demo
              run: |
                 echo " The name of the event ${{github.event.inputs.name}}"
                 echo " The second name of the version is ${{github.event.inputs.version}}"
                 echo " The name of the person is ${{env.data}} and ready to ${{env.fame}}"
