name : Test Workflow
on :
    workflow_dispatch:
        inputs:
            name:
                description : "Entet the name"
                required : true
                default : :GitHub User"
                type : string
jobs:
    test:
        runs-on : ubuntu-latest
        steps:
            - name: Demo
              run: echo " The name of the event ${{github.event.inputs.name}}"
